/* ==========================================================================
   Ghoomgali Itinerary Maker - sample plans
   Four trips, each written a different way, so the agent can see which
   styles of text the reader understands: pipes and brackets (Vietnam),
   "Day 1: date - title" with timing lines and a fixed package price
   (Thailand), "Day One" words with prices in the line (Bali), and "1st Day"
   with flights and per-person working (Dubai). The agency's own samples,
   saved from the Paste tab, are listed after these.
   ========================================================================== */
(function () {
  'use strict';

  var vietnam = [
    'Vietnam *Escape.*',
    'Hanoi · Danang · Phu Quoc — an 8-day journey for 5',
    'Nov 22–29 | 8D / 7N | 5 adults | 2 children | 3 cities',
    '',
    'Hotels',
    'Hanoi | Sky Lark Hotel, Hanoi | Nov 22 – 24 | 2 nights | 21533',
    '- 1 x Superior Room, Double Bed (No window)',
    '- 1 x Triple Deluxe Room (with Window)',
    '- Breakfast included',
    '',
    'Danang | Santa Luxury Hotel, Danang | Nov 24 – 26 | 2 nights | 19382',
    '- 2 x Double or Twin Room (with Sea View)',
    '- Breakfast included',
    '',
    'Phu Quoc | Azura Resort, Phu Quoc | Nov 26 – 29 | 3 nights | 31441',
    '- 1 x Deluxe Triple Room (with Balcony)',
    '- 1 x Standard Room (with Balcony)',
    '- Breakfast included',
    '',
    'Day 1 | November 22 · Hanoi | Hanoi',
    '[On arrival · coordinated with flight]',
    'HAN Airport Pick-Up | 2100',
    'Arrival and private transfer from Hanoi (HAN) Airport to the hotel.',
    '- Private transfer vehicle',
    '',
    '[Half day · pick-up time to be confirmed]',
    'Hanoi City Half-Day Tour | 11590',
    'Guided sightseeing covering key locations across Hanoi City.',
    '- Shuttle bus transport',
    '- Seat-in-coach (SIC) format',
    '= INR 2,318 × 5 adults',
    '',
    'Day 2 | November 23 · Hanoi · Halong Bay | Hanoi / Halong Bay',
    '[Full day · morning pick-up to be confirmed]',
    'Halong Bay Luxury Day Cruise | 23500',
    'Excursion to Halong Bay featuring scenic cruising, a sunset party and kayaking.',
    '- Limo bus transport (SIC)',
    '- Luxury day cruise',
    '- Kayaking access',
    '- Buffet lunch',
    '- Sunset party',
    '= INR 4,700 × 5 adults',
    '',
    'Day 3 | November 24 · Hanoi → Danang | Hanoi to Danang',
    '[Coordinated with domestic flight]',
    'Hanoi → Danang Airport Transfers | 4200',
    'Hotel check-out, transfer to HAN Airport, and pick-up at DAD Airport on arrival in Danang.',
    '- Private transfer vehicle — HAN drop-off',
    '- Private transfer vehicle — DAD pick-up',
    '= INR 2,100 + INR 2,100',
    '',
    '[15:30 – 21:00]',
    'Marble Mountain + Hoi An Ancient Town | 12500',
    'Evening sightseeing of Marble Mountain followed by an exploration of Hoi An Ancient Town.',
    '- Seat-in-coach (SIC) transport',
    '- Guided tour',
    '- Local dinner',
    '= INR 2,500 × 5 adults',
    '',
    'Day 4 | November 25 · Danang | Danang',
    '[Full day · morning pick-up to be confirmed]',
    'Ba Na Hills Day Trip | 19500',
    'Exploration of Ba Na Hills, including the Golden Hands Bridge, French Village and Fantasy Park.',
    '- Seat-in-coach (SIC) transport',
    '- Round-trip cable car ride',
    '- Entry — Golden Hands Bridge, Fantasy Park & French Village',
    '= INR 3,900 × 5 adults · lunch not included',
    '',
    'Day 5 | November 26 · Danang → Phu Quoc | Danang to Phu Quoc',
    '[Coordinated with domestic flight]',
    'Danang → Phu Quoc Airport Transfers | 4200',
    'Hotel check-out, transfer to DAD Airport, and pick-up at PQC Airport on arrival in Phu Quoc.',
    '- Private transfer vehicle — DAD drop-off',
    '- Private transfer vehicle — PQC pick-up',
    '= INR 2,100 + INR 2,100',
    '',
    '[Afternoon / evening · pick-up to be confirmed]',
    'Grandworld Phu Quoc Visit | 4901',
    'Independent visit to Grandworld Phu Quoc from Central Phu Quoc.',
    '- Round-trip transport from Central PQ',
    '= Guide not included',
    '',
    'Day 6 | November 27 · Phu Quoc | Phu Quoc',
    '[Full day · morning pick-up to be confirmed]',
    'VinWonders + VinSafari Experience | 35000',
    'Visit to the VinWonders theme park and the VinSafari wildlife conservation park.',
    '- Round-trip transport from Central PQ (no guide)',
    '- Entry — VinWonders',
    '- Entry — VinSafari',
    '= Transport INR 6,500 + Tickets INR 28,500 (INR 5,700 × 5 adults)',
    '',
    'Day 7 | November 28 · Phu Quoc | Phu Quoc',
    '[Full day · morning pick-up to be confirmed]',
    '4 Island Hopping Tour | 30000',
    'Boat excursion to explore four islands around Phu Quoc.',
    '- Seat-in-coach (SIC) transport',
    '- Boat access',
    '- One-way cable car ride',
    '- Local lunch',
    '= INR 6,000 × 5 adults',
    '',
    'Day 8 | November 29 · Departure | Departure',
    '[Coordinated with departure flight]',
    'PQC Airport Drop-Off | 2100',
    'Hotel check-out and departure transfer from Central Phu Quoc to PQC Airport.',
    '- Private transfer vehicle',
    '',
    'Pricing',
    'Margin | 45000',
    'GST | 5%',
    'TCS | 2%',
    'Discount | 5000',
    '',
    'Terms',
    'Cancellations accepted up to 7 days before departure; non-refundable components are deducted first.',
    'Flights, including any internal transfers, are not included and must be arranged independently.',
    'Hotel check-in is from 2:00 PM and check-out by 11:00 AM.',
    '',
    'Notes',
    'Domestic flights within Vietnam are quoted separately and confirmed once dates are locked.',
    'E-visa approval letters take five working days — please share passport scans early.'
  ].join('\n');

  var thailand = [
    'Thailand *Island Hop.*',
    'Phuket · Krabi · Bangkok — 7 days for a family of four',
    'Jan 12–18 | 7D / 6N | 2 adults | 2 children | 3 cities',
    '',
    'Hotels',
    'Phuket | Novotel Phuket Kamala Beach | Jan 12 – 14 | 2 nights | Rs 28,000',
    '- 1 x Family Room (2 adults + 2 children)',
    '- Breakfast included',
    '',
    'Krabi | Holiday Inn Resort Krabi Ao Nang | Jan 14 – 16 | 2 nights | Rs 24,500',
    '- 1 x Family Suite',
    '- Breakfast included',
    '',
    'Bangkok | Novotel Bangkok Sukhumvit 20 | Jan 16 – 18 | 2 nights | Rs 21,000',
    '- 1 x Superior Room with extra bed',
    '- Breakfast included',
    '',
    'Day 1: 12 Jan - Arrival in Phuket',
    'Flight 6E-1061 DEL to HKT 00:45 - 06:55',
    'Phuket Airport Pick-Up | Rs 1,800',
    'Private transfer from Phuket International Airport to the hotel in Kamala.',
    'Evening',
    'Kamala Beach sunset walk',
    'A free evening on the beach.',
    '',
    'Day 2: 13 Jan - Phi Phi Islands',
    'Full day',
    'Phi Phi Island Tour by Speedboat | Rs 14,400',
    'Maya Bay, Pileh Lagoon, Viking Cave and snorkelling at Bamboo Island.',
    '- Hotel pick-up and drop (SIC)',
    '- Lunch on the island',
    '- Snorkel gear',
    '= Rs 3,600 × 4 travelers',
    '',
    'Day 3: 14 Jan - Phuket to Krabi',
    '09:30',
    'Phuket to Krabi Private Transfer | Rs 3,500',
    'About three hours by road, with a stop at a viewpoint.',
    'Afternoon',
    'Ao Nang beach at leisure',
    '',
    'Day 4: 15 Jan - Krabi 4 Islands',
    'Full day',
    'Krabi 4 Islands Longtail Tour | Rs 8,800',
    'Phra Nang Cave Beach, Chicken Island, Tup Island and Poda Island.',
    '- Longtail boat',
    '- Packed lunch',
    '= Rs 2,200 × 4 travelers',
    '',
    'Day 5: 16 Jan - Fly to Bangkok',
    'Krabi Hotel to Airport | Rs 1,500',
    'Flight FD-3214 KBV to DMK 11:20 - 12:35 | Rs 9,600',
    'Don Mueang Airport to Hotel | Rs 1,700',
    'Evening',
    'Asiatique The Riverfront',
    'Night market and the Ferris wheel by the river.',
    '',
    'Day 6: 17 Jan - Temples and Safari World',
    'Morning',
    'Grand Palace & Wat Pho Tour | Rs 7,200',
    '- English-speaking guide',
    '= Rs 1,800 × 4 travelers',
    '',
    'Afternoon',
    'Safari World & Marine Park | Rs 10,400',
    '= Rs 2,600 × 4 travelers',
    '',
    'Day 7: 18 Jan - Departure',
    'Hotel to Suvarnabhumi Airport | Rs 1,700',
    'Flight 6E-1052 BKK to DEL 23:30 - 02:55',
    '',
    'Pricing',
    'Total | Rs 1,45,000 incl. GST',
    'TCS | 5%',
    '',
    'Inclusions',
    'Daily breakfast at all hotels',
    'All transfers and tours as listed',
    '',
    'Exclusions',
    'International flights',
    'Thailand visa fees'
  ].join('\n');

  var bali = [
    'Bali *Honeymoon.*',
    'Ubud · Nusa Penida · Seminyak — six days for two',
    'March 3–8 | 6D / 5N | 2 adults | 2 cities',
    '',
    'Stay',
    'Ubud | Maya Ubud Resort & Spa | Mar 3 – 5 | 2 nights | ₹38,000',
    '- Deluxe Room, River View',
    '- Breakfast included',
    '',
    'Seminyak | W Bali Seminyak | Mar 5 – 8 | 3 nights | ₹72,000',
    '- Wonderful Garden Escape',
    '- Breakfast included',
    '',
    'Day One — 3rd March, Arrival in Bali',
    'On arrival',
    'Airport pick-up to Ubud ₹2,200',
    'Private car with a flower-garland welcome.',
    'Evening',
    'Candle-light dinner by the river ₹6,500',
    '- Set menu for two',
    '',
    'Day Two — 4th March, Kintamani and the coffee trail',
    'Morning',
    'Kintamani volcano and Tegenungan waterfall ₹7,800',
    '- Private car and driver for the day',
    '- Entry tickets',
    'Afternoon',
    'Luwak coffee plantation visit',
    'Lunch overlooking Mount Batur ₹3,000',
    '',
    'Day Three — 5th March, Ubud to Seminyak',
    '10:00',
    'Ubud swing and rice terraces, then on to Seminyak ₹5,500',
    '',
    'Day Four — 6th March, Nusa Penida',
    'Full day',
    'West Nusa Penida day trip ₹16,000',
    'Kelingking Beach, Broken Beach and Angel\'s Billabong.',
    '- Fast boat both ways',
    '- Private car on the island',
    '- Lunch',
    '',
    'Day Five — 7th March, Seminyak',
    'Evening',
    'Tanah Lot sunset tour ₹4,200',
    '',
    'Day Six — 8th March, Departure',
    'Hotel to airport drop ₹1,800',
    '',
    'Pricing',
    'Margin | 18000',
    'GST | 5%',
    'TCS | 5%'
  ].join('\n');

  var dubai = [
    'Dubai *Family Fun.*',
    'Dubai · Abu Dhabi — five days for a family of four',
    'Dec 20–24 | 5D / 4N | 2 adults | 2 kids | 2 cities',
    '',
    'Hotels',
    'Dubai | Rove Downtown | Dec 20 – 24 | 4 nights | INR 52,000',
    '- 1 x Family Room (2 adults + 2 children)',
    '- Breakfast included',
    '',
    '1st Day | Dec 20 · Dubai | Welcome to Dubai',
    '[Before travel]',
    'UAE Tourist Visa (30 days) | 26000',
    '= INR 6,500 × 4 travelers',
    '',
    'Flight EK-511 DEL to DXB 04:15 - 06:20 | 88000',
    'Emirates economy, 30 kg baggage each.',
    '',
    '[On arrival]',
    'DXB Airport to Hotel | 2400',
    'Private 7-seater vehicle.',
    '',
    '[Evening]',
    'Dhow Cruise Dinner at Marina | 9600',
    '- Buffet dinner',
    '- Live entertainment',
    '= INR 2,400 × 4 travelers',
    '',
    '2nd Day | Dec 21 · Dubai | Desert Safari',
    '[Morning]',
    'Dubai City Tour (SIC) | 6000',
    'Jumeirah Mosque, a Dubai Frame photo stop and the Gold Souk.',
    '',
    '[15:00 – 21:00]',
    'Evening Desert Safari with BBQ Dinner | 11200',
    '- Dune bashing, camel ride and sandboarding',
    '- Tanoura and fire show',
    '= INR 2,800 × 4 travelers',
    '',
    '3rd Day | Dec 22 · Abu Dhabi | Abu Dhabi day trip',
    '[Full day]',
    'Abu Dhabi City Tour + Ferrari World | 26000',
    'Sheikh Zayed Grand Mosque, then Ferrari World on Yas Island.',
    '= Adults INR 7,500 × 2 + Children INR 5,500 × 2',
    '',
    '4th Day | Dec 23 · Dubai | Burj Khalifa and the Aquarium',
    '[Afternoon]',
    'Burj Khalifa 124th floor + Dubai Aquarium | 14800',
    '',
    '[Evening]',
    'Dubai Fountain show and Dubai Mall at leisure',
    '',
    '5th Day | Dec 24 · Departure | Fly home',
    'Hotel to DXB Airport | 2400',
    'Flight EK-510 DXB to DEL 22:10 - 02:45',
    '',
    'Pricing',
    'Margin | 30000',
    'GST | 5%',
    'TCS | 5%',
    'Discount | 3000'
  ].join('\n');

  window.GGSamples = [
    { id: 'vietnam', name: 'Vietnam · 8 days · pipes and brackets', text: vietnam },
    { id: 'thailand', name: 'Thailand · 7 days · fixed price incl. GST', text: thailand },
    { id: 'bali', name: 'Bali honeymoon · 6 days · "Day One" style', text: bali },
    { id: 'dubai', name: 'Dubai family · 5 days · with flights', text: dubai }
  ];
})();
